name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build and test with JaCoCo
      run: |
        mkdir -p temp
        mvn clean test jacoco:report | tee temp/build.log

    - name: Create build summary
      run: |
        echo "### Build & Coverage Report" > temp/summary.md
        echo "**Test output (ultime righe):**" >> temp/summary.md
        echo '```' >> temp/summary.md
        tail -n 15 temp/build.log >> temp/summary.md
        echo '```' >> temp/summary.md
        echo "**Coverage (linee):**" >> temp/summary.md
        grep -A1 "Total" target/site/jacoco/index.html | tail -n1 | sed 's/<[^>]*>//g' >> temp/summary.md

    - name: Update README.md
      run: |
        START="<!-- BUILD-REPORT-START -->"
        END="<!-- BUILD-REPORT-END -->"
        REPORT=$(cat temp/summary.md)

        if grep -q "$START" README.md; then
          sed -i "/$START/,/$END/c\\$START\n$REPORT\n$END" README.md
        else
          echo -e "\n$START\n$REPORT\n$END" >> README.md
        fi

    - name: Commit updated README.md
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add README.md
        git diff --quiet || git commit -m "Aggiorna README.md con risultati build"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
