name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build and test with JaCoCo
      run: |
        mkdir -p temp
        mvn clean verify jacoco:report checkstyle:checkstyle | tee temp/build.log

    - name: Create build summary and script for the re-writing of the README.md file
      run: |
        echo "### Build & Coverage Report" > temp/summary.md
        echo "**Log finale Maven (ultime righe):**" >> temp/summary.md
        echo '```' >> temp/summary.md
        tail -n 15 temp/build.log >> temp/summary.md
        echo '```' >> temp/summary.md
        if [ -f target/site/jacoco/jacoco.csv ]; then
          echo '```csv' >> temp/summary.md
          head -n 1 target/site/jacoco/jacoco.csv >> temp/summary.md     # intestazione
          tail -n +2 target/site/jacoco/jacoco.csv >> temp/summary.md    # contenuto
          echo '```' >> temp/summary.md
        else
          echo "_File jacoco.csv non trovato._" >> temp/summary.md
        fi
        echo "**Violazioni Checkstyle:**" >> temp/summary.md
        CHECKSTYLE_ERRORS=$(grep -o 'severity="error"' target/checkstyle-result.xml | wc -l)
        echo "Errori rilevati: $CHECKSTYLE_ERRORS" >> temp/summary.md
        START="<!-- BUILD-REPORT-START -->"
        END="<!-- BUILD-REPORT-END -->"
        REPORT=$(cat temp/summary.md)
        if grep -q "$START" README.md; then
          sed -i.bak "/$START/,/$END/c\\$START\n$REPORT\n$END" README.md
        else
        echo -e "\n$START\n$REPORT\n$END" >> README.md
        fi
        
    - name: Commit updated README.md
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git fetch
        git checkout ${{ github.head_ref || github.ref_name }}
        git add README.md
        git commit -m "Aggiorna README.md con risultati build"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.head_ref || github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
